### ISSUE TITLE
Migrating user .... to new data format keeps appearing non-stop/spam

### ISSUE THREAD

**Issue by WolfLiSteel** [AdvancedPlugins/Jobs#43]
### Describe the bug

[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad6d6e47-13af-4abe-b96e-573cca76703d to new data format.

This keeps repeating non-stop. You will notice that its the same users.

[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad6d6e47-13af-4abe-b96e-573cca76703d to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad08cf60-798f-42c3-9c76-9577e6344a93 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 00000000-0000-0000-0009-00000e5e0ba2 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 189b864b-58c1-4110-9edd-4d09d6163a1d to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user f556c52a-fc79-4974-ac83-8dadc54acbf7 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 40e1f417-b8a9-4c93-a8c5-82769031d982 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user b10f3ac9-696f-4d9b-9157-d975e1bc7ce7 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 482b634e-7e94-4a2e-801b-1a100ef24876 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user a3e11b98-b6c0-4fa7-9218-7744d89b8935 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user bd0750c5-0ece-4354-a54d-ffd4bf12d0b5 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user d69de5b8-f905-449c-92e2-35d0969f27a6 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 8d03441e-39b7-4579-afd7-3e35cc14c369 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 37ac2ded-3573-4083-8a71-e1e5f4f1f5b5 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 00000000-0000-0000-0009-01f32fdd8bc4 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 3b8d543d-a13b-4a44-a87e-73f1c0451bed to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 32e85d12-d149-448c-a81d-a9192f053c14 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 6bdf7c8a-7893-4806-8988-bc55eec6803e to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 2794a9d2-6f02-43c3-85f9-bdb3265510cc to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 35bcc97a-49a1-4012-a027-4dc0d27f1445 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user eb6d564e-277a-47af-99eb-b8c2e4728928 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user d146a1a3-0bc2-4ce2-ac18-ae51ed441882 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user f74a00d2-33db-4ee7-9355-715c232061b3 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad6d6e47-13af-4abe-b96e-573cca76703d to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad08cf60-798f-42c3-9c76-9577e6344a93 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 00000000-0000-0000-0009-00000e5e0ba2 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 189b864b-58c1-4110-9edd-4d09d6163a1d to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user f556c52a-fc79-4974-ac83-8dadc54acbf7 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 40e1f417-b8a9-4c93-a8c5-82769031d982 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user b10f3ac9-696f-4d9b-9157-d975e1bc7ce7 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 482b634e-7e94-4a2e-801b-1a100ef24876 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user a3e11b98-b6c0-4fa7-9218-7744d89b8935 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user bd0750c5-0ece-4354-a54d-ffd4bf12d0b5 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user d69de5b8-f905-449c-92e2-35d0969f27a6 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 8d03441e-39b7-4579-afd7-3e35cc14c369 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 37ac2ded-3573-4083-8a71-e1e5f4f1f5b5 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 00000000-0000-0000-0009-01f32fdd8bc4 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 3b8d543d-a13b-4a44-a87e-73f1c0451bed to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 32e85d12-d149-448c-a81d-a9192f053c14 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 6bdf7c8a-7893-4806-8988-bc55eec6803e to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 2794a9d2-6f02-43c3-85f9-bdb3265510cc to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user 35bcc97a-49a1-4012-a027-4dc0d27f1445 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user eb6d564e-277a-47af-99eb-b8c2e4728928 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user d146a1a3-0bc2-4ce2-ac18-ae51ed441882 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user f74a00d2-33db-4ee7-9355-715c232061b3 to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad6d6e47-13af-4abe-b96e-573cca76703d to new data format
[12:29:53] [Craft Scheduler Thread - 49 - AdvancedJobs/INFO]: Migrating user ad08cf60-798f-42c3-9c76-9577e6344a93 to new data format

### How to reproduce

Latest advjobs AdvancedJobs-1.3.8. Default plugin setup.
Latest paper 
[16:05:36 INFO]: This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-101-5fee9c6 (MC: 1.21)

### Server Log

https://mcpaste.io/d699bd7e587505b3

**Comment by WolfLiSteel** [comment]
users-storage

[00000000-0000-0000-0009-00000e5e0ba2.json](https://github.com/user-attachments/files/16364957/00000000-0000-0000-0009-00000e5e0ba2.json)
[00000000-0000-0000-0009-01f32fdd8bc4.json](https://github.com/user-attachments/files/16364958/00000000-0000-0000-0009-01f32fdd8bc4.json)
[3b8d543d-a13b-4a44-a87e-73f1c0451bed.json](https://github.com/user-attachments/files/16364959/3b8d543d-a13b-4a44-a87e-73f1c0451bed.json)
[6bdf7c8a-7893-4806-8988-bc55eec6803e.json](https://github.com/user-attachments/files/16364960/6bdf7c8a-7893-4806-8988-bc55eec6803e.json)
[8d03441e-39b7-4579-afd7-3e35cc14c369.json](https://github.com/user-attachments/files/16364961/8d03441e-39b7-4579-afd7-3e35cc14c369.json)
[32e85d12-d149-448c-a81d-a9192f053c14.json](https://github.com/user-attachments/files/16364962/32e85d12-d149-448c-a81d-a9192f053c14.json)
[35bcc97a-49a1-4012-a027-4dc0d27f1445.json](https://github.com/user-attachments/files/16364963/35bcc97a-49a1-4012-a027-4dc0d27f1445.json)
[37ac2ded-3573-4083-8a71-e1e5f4f1f5b5.json](https://github.com/user-attachments/files/16364964/37ac2ded-3573-4083-8a71-e1e5f4f1f5b5.json)
[40e1f417-b8a9-4c93-a8c5-82769031d982.json](https://github.com/user-attachments/files/16364965/40e1f417-b8a9-4c93-a8c5-82769031d982.json)
[189b864b-58c1-4110-9edd-4d09d6163a1d.json](https://github.com/user-attachments/files/16364966/189b864b-58c1-4110-9edd-4d09d6163a1d.json)
[482b634e-7e94-4a2e-801b-1a100ef24876.json](https://github.com/user-attachments/files/16364967/482b634e-7e94-4a2e-801b-1a100ef24876.json)
[2794a9d2-6f02-43c3-85f9-bdb3265510cc.json](https://github.com/user-attachments/files/16364968/2794a9d2-6f02-43c3-85f9-bdb3265510cc.json)
[a3e11b98-b6c0-4fa7-9218-7744d89b8935.json](https://github.com/user-attachments/files/16364969/a3e11b98-b6c0-4fa7-9218-7744d89b8935.json)
[ad6d6e47-13af-4abe-b96e-573cca76703d.json](https://github.com/user-attachments/files/16364970/ad6d6e47-13af-4abe-b96e-573cca76703d.json)
[ad08cf60-798f-42c3-9c76-9577e6344a93.json](https://github.com/user-attachments/files/16364971/ad08cf60-798f-42c3-9c76-9577e6344a93.json)
[b10f3ac9-696f-4d9b-9157-d975e1bc7ce7.json](https://github.com/user-attachments/files/16364973/b10f3ac9-696f-4d9b-9157-d975e1bc7ce7.json)
[bd0750c5-0ece-4354-a54d-ffd4bf12d0b5.json](https://github.com/user-attachments/files/16364974/bd0750c5-0ece-4354-a54d-ffd4bf12d0b5.json)
[d69de5b8-f905-449c-92e2-35d0969f27a6.json](https://github.com/user-attachments/files/16364975/d69de5b8-f905-449c-92e2-35d0969f27a6.json)
[d146a1a3-0bc2-4ce2-ac18-ae51ed441882.json](https://github.com/user-attachments/files/16364976/d146a1a3-0bc2-4ce2-ac18-ae51ed441882.json)
[eb6d564e-277a-47af-99eb-b8c2e4728928.json](https://github.com/user-attachments/files/16364977/eb6d564e-277a-47af-99eb-b8c2e4728928.json)
[f74a00d2-33db-4ee7-9355-715c232061b3.json](https://github.com/user-attachments/files/16364978/f74a00d2-33db-4ee7-9355-715c232061b3.json)
[f556c52a-fc79-4974-ac83-8dadc54acbf7.json](https://github.com/user-attachments/files/16364979/f556c52a-fc79-4974-ac83-8dadc54acbf7.json)

**Comment by WolfLiSteel** [comment]
Config

https://mcpaste.io/ecd4eca17db66db5

**Comment by itzMiney** [comment]
This issue is happening to me too I and confirmed it was definitely the AdvancedJobs plugin by running `zgrep  "to new data format" *` in the logs folder
![grafik](https://github.com/user-attachments/assets/0e661749-e96b-42bc-97df-34bab2cbefcc)

**Comment by itzMiney** [comment]
Good news @WolfLiSteel GC said in a ticket that they'll release a new version today where this is hopefully fixed

**Comment by KPGTB** [comment]
Hey! I fixed migration problem - fix will be available in the next update. Sorry for the inconvenience, but I couldn't fix it faster, because I was on vacation.

kpg_tb

**Comment by WolfLiSteel** [comment]
No worries. and thank you for fixing it.

**Comment by itzMiney** [comment]
Did it get fixed for you at least @WolfLiSteel ? for me the issue still persists at least..
![grafik](https://github.com/user-attachments/assets/bd8d0737-c1e6-4e1e-92dd-2c9b09357962)
![grafik](https://github.com/user-attachments/assets/22af530b-ecde-4cf0-8304-5105e65567f7)

**Comment by WolfLiSteel** [comment]
Nope. Still the same. Still havent been fix. But I dont see anything about it being fixed in the changelog. So Im not sure if it has been fixed. And the problem is still there.
